name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt install libcurl4-openssl-dev libssl-dev -y
    - name: build and test
      run: ./build.sh
